package dao;
import conexion.ConexionMySQL; import modelo.Diagnostico; import java.sql.*; import java.util.*;
public class DiagnosticoDAO {
 public boolean registrar(Diagnostico d){String sql="INSERT INTO diagnosticos(codigo_diagnostico,id_orden,id_tecnico,descripcion_diagnostico,solucion_aplicada,repuestos_utilizados,fecha_diagnostico,estado) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=ConexionMySQL.conectar()){c.setAutoCommit(false);String cod=CodigoDAOUtil.siguiente(c,"diagnosticos","codigo_diagnostico","DIAG");try(PreparedStatement p=c.prepareStatement(sql)){p.setString(1,cod);cargar(p,d,2);boolean ok=p.executeUpdate()>0;c.commit();return ok;}catch(Exception x){c.rollback();throw x;}}catch(Exception x){System.out.println("Error registrar diagnostico: "+x.getMessage());return false;}}
 public List<Diagnostico> listar(){List<Diagnostico> l=new ArrayList<>();String sql="SELECT d.*,o.codigo_orden,u.dni dni_tecnico,u.nombre tecnico FROM diagnosticos d JOIN ordenes_servicio o ON o.id_orden=d.id_orden JOIN usuarios u ON u.id_usuario=d.id_tecnico ORDER BY d.id_diagnostico DESC";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql);ResultSet r=p.executeQuery()){while(r.next())l.add(map(r));}catch(SQLException x){System.out.println("Error listar diagnosticos: "+x.getMessage());}return l;}
 public boolean actualizar(Diagnostico d){String sql="UPDATE diagnosticos SET id_orden=?,id_tecnico=?,descripcion_diagnostico=?,solucion_aplicada=?,repuestos_utilizados=?,fecha_diagnostico=?,estado=? WHERE id_diagnostico=?";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){cargar(p,d,1);p.setInt(8,d.getIdDiagnostico());return p.executeUpdate()>0;}catch(SQLException x){System.out.println("Error actualizar diagnostico: "+x.getMessage());return false;}}
 public boolean eliminar(int id){try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement("DELETE FROM diagnosticos WHERE id_diagnostico=?")){p.setInt(1,id);return p.executeUpdate()>0;}catch(SQLException x){System.out.println("Error eliminar diagnostico: "+x.getMessage());return false;}}
 public Diagnostico buscarPorId(int id){String sql="SELECT d.*,o.codigo_orden,u.dni dni_tecnico,u.nombre tecnico FROM diagnosticos d JOIN ordenes_servicio o ON o.id_orden=d.id_orden JOIN usuarios u ON u.id_usuario=d.id_tecnico WHERE d.id_diagnostico=?";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}catch(SQLException x){return null;}}
 private void cargar(PreparedStatement p,Diagnostico d,int i)throws SQLException{p.setInt(i++,d.getIdOrden());p.setInt(i++,d.getIdTecnico());p.setString(i++,d.getDescripcionDiagnostico());p.setString(i++,d.getSolucionAplicada());p.setString(i++,d.getRepuestosUtilizados());p.setString(i++,d.getFechaDiagnostico());p.setString(i,d.getEstado()==null||d.getEstado().isBlank()?"Pendiente":d.getEstado());}
 private Diagnostico map(ResultSet r)throws SQLException{Diagnostico d=new Diagnostico();d.setIdDiagnostico(r.getInt("id_diagnostico"));d.setCodigoDiagnostico(r.getString("codigo_diagnostico"));d.setIdOrden(r.getInt("id_orden"));d.setIdTecnico(r.getInt("id_tecnico"));d.setCodigoOrden(r.getString("codigo_orden"));d.setTecnicoDni(r.getString("dni_tecnico"));d.setTecnicoNombre(r.getString("tecnico"));d.setDescripcionDiagnostico(r.getString("descripcion_diagnostico"));d.setSolucionAplicada(r.getString("solucion_aplicada"));d.setRepuestosUtilizados(r.getString("repuestos_utilizados"));d.setFechaDiagnostico(r.getString("fecha_diagnostico"));d.setEstado(r.getString("estado"));return d;}
}
