package dao;
import conexion.ConexionMySQL; import modelo.Equipo; import java.sql.*; import java.util.*;
public class EquipoDAO {
 public boolean registrar(Equipo e){String sql="INSERT INTO equipos(codigo_equipo,id_cliente,tipo_equipo,marca,modelo,serie,descripcion,estado) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=ConexionMySQL.conectar()){c.setAutoCommit(false);String cod=CodigoDAOUtil.siguiente(c,"equipos","codigo_equipo","EQ");try(PreparedStatement p=c.prepareStatement(sql)){p.setString(1,cod);cargar(p,e,2);boolean ok=p.executeUpdate()>0;c.commit();return ok;}catch(Exception x){c.rollback();throw x;}}catch(Exception x){System.out.println("Error registrar equipo: "+x.getMessage());return false;}}
 public List<Equipo> listar(){List<Equipo> l=new ArrayList<>();String sql="SELECT e.*,c.dni dni_cliente,CONCAT(c.nombres,' ',c.apellidos) cliente FROM equipos e JOIN clientes c ON c.id_cliente=e.id_cliente ORDER BY e.id_equipo DESC";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql);ResultSet r=p.executeQuery()){while(r.next())l.add(map(r));}catch(SQLException x){System.out.println("Error listar equipos: "+x.getMessage());}return l;}
 public boolean actualizar(Equipo e){String sql="UPDATE equipos SET id_cliente=?,tipo_equipo=?,marca=?,modelo=?,serie=?,descripcion=?,estado=? WHERE id_equipo=?";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){cargar(p,e,1);p.setInt(8,e.getIdEquipo());return p.executeUpdate()>0;}catch(SQLException x){System.out.println("Error actualizar equipo: "+x.getMessage());return false;}}
 public boolean eliminar(int id){try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement("DELETE FROM equipos WHERE id_equipo=?")){p.setInt(1,id);return p.executeUpdate()>0;}catch(SQLException x){System.out.println("Error eliminar equipo: "+x.getMessage());return false;}}
 public Equipo buscarPorId(int id){String sql="SELECT e.*,c.dni dni_cliente,CONCAT(c.nombres,' ',c.apellidos) cliente FROM equipos e JOIN clientes c ON c.id_cliente=e.id_cliente WHERE e.id_equipo=?";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}catch(SQLException x){return null;}}
 private void cargar(PreparedStatement p,Equipo e,int i)throws SQLException{p.setInt(i++,e.getIdCliente());p.setString(i++,e.getTipoEquipo());p.setString(i++,e.getMarca());p.setString(i++,e.getModelo());if(e.getSerie()==null||e.getSerie().isBlank())p.setNull(i++,Types.VARCHAR);else p.setString(i++,e.getSerie());p.setString(i++,e.getDescripcion());p.setString(i,e.getEstado());}
 private Equipo map(ResultSet r)throws SQLException{Equipo e=new Equipo();e.setIdEquipo(r.getInt("id_equipo"));e.setCodigoEquipo(r.getString("codigo_equipo"));e.setIdCliente(r.getInt("id_cliente"));e.setClienteDni(r.getString("dni_cliente"));e.setClienteNombre(r.getString("cliente"));e.setTipoEquipo(r.getString("tipo_equipo"));e.setMarca(r.getString("marca"));e.setModelo(r.getString("modelo"));e.setSerie(r.getString("serie"));e.setDescripcion(r.getString("descripcion"));e.setEstado(r.getString("estado"));e.setFechaRegistro(r.getString("fecha_registro"));return e;}
}
