package dao;
import conexion.ConexionMySQL; import modelo.OrdenServicio; import java.sql.*; import java.util.*;
public class OrdenServicioDAO {
 public boolean registrar(OrdenServicio o){String sql="INSERT INTO ordenes_servicio(codigo_orden,id_cliente,id_equipo,id_tecnico,fecha_registro,problema_reportado,observaciones,estado) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=ConexionMySQL.conectar()){c.setAutoCommit(false);String cod=CodigoDAOUtil.siguiente(c,"ordenes_servicio","codigo_orden","ORD");try(PreparedStatement p=c.prepareStatement(sql)){p.setString(1,cod);cargar(p,o,2);boolean ok=p.executeUpdate()>0;c.commit();return ok;}catch(Exception x){c.rollback();throw x;}}catch(Exception x){System.out.println("Error registrar orden: "+x.getMessage());return false;}}
 public List<OrdenServicio> listar(){List<OrdenServicio> l=new ArrayList<>();String sql="SELECT o.*,c.dni dni_cliente,CONCAT(c.nombres,' ',c.apellidos) cliente,e.codigo_equipo,CONCAT(e.marca,' ',e.modelo) equipo,u.dni dni_tecnico,u.nombre tecnico FROM ordenes_servicio o JOIN clientes c ON c.id_cliente=o.id_cliente JOIN equipos e ON e.id_equipo=o.id_equipo JOIN usuarios u ON u.id_usuario=o.id_tecnico ORDER BY o.id_orden DESC";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql);ResultSet r=p.executeQuery()){while(r.next())l.add(map(r));}catch(SQLException x){System.out.println("Error listar ordenes: "+x.getMessage());}return l;}
 public boolean actualizar(OrdenServicio o){String sql="UPDATE ordenes_servicio SET id_cliente=?,id_equipo=?,id_tecnico=?,fecha_registro=?,problema_reportado=?,observaciones=?,estado=? WHERE id_orden=?";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){cargar(p,o,1);p.setInt(8,o.getIdOrden());return p.executeUpdate()>0;}catch(SQLException x){System.out.println("Error actualizar orden: "+x.getMessage());return false;}}
 public boolean eliminar(int id){try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement("DELETE FROM ordenes_servicio WHERE id_orden=?")){p.setInt(1,id);return p.executeUpdate()>0;}catch(SQLException x){System.out.println("Error eliminar orden: "+x.getMessage());return false;}}
 public OrdenServicio buscarPorId(int id){String sql="SELECT o.*,c.dni dni_cliente,CONCAT(c.nombres,' ',c.apellidos) cliente,e.codigo_equipo,CONCAT(e.marca,' ',e.modelo) equipo,u.dni dni_tecnico,u.nombre tecnico FROM ordenes_servicio o JOIN clientes c ON c.id_cliente=o.id_cliente JOIN equipos e ON e.id_equipo=o.id_equipo JOIN usuarios u ON u.id_usuario=o.id_tecnico WHERE o.id_orden=?";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}catch(SQLException x){return null;}}
 private void cargar(PreparedStatement p,OrdenServicio o,int i)throws SQLException{p.setInt(i++,o.getIdCliente());p.setInt(i++,o.getIdEquipo());p.setInt(i++,o.getIdTecnico());p.setString(i++,o.getFechaRegistro());p.setString(i++,o.getProblemaReportado());if(o.getObservaciones()==null||o.getObservaciones().isBlank())p.setNull(i++,Types.VARCHAR);else p.setString(i++,o.getObservaciones());p.setString(i,o.getEstado());}
 private OrdenServicio map(ResultSet r)throws SQLException{OrdenServicio o=new OrdenServicio();o.setIdOrden(r.getInt("id_orden"));o.setCodigoOrden(r.getString("codigo_orden"));o.setIdCliente(r.getInt("id_cliente"));o.setIdEquipo(r.getInt("id_equipo"));o.setIdTecnico(r.getInt("id_tecnico"));o.setClienteDni(r.getString("dni_cliente"));o.setClienteNombre(r.getString("cliente"));o.setCodigoEquipo(r.getString("codigo_equipo"));o.setEquipoNombre(r.getString("equipo"));o.setTecnicoDni(r.getString("dni_tecnico"));o.setTecnicoNombre(r.getString("tecnico"));o.setFechaRegistro(r.getString("fecha_registro"));o.setProblemaReportado(r.getString("problema_reportado"));o.setObservaciones(r.getString("observaciones"));o.setEstado(r.getString("estado"));return o;}
}
