package dao;
import conexion.ConexionMySQL; import modelo.Pago; import java.sql.*; import java.util.*;
public class PagoDAO {
 public boolean registrar(Pago x){String sql="INSERT INTO pagos(codigo_pago,id_orden,monto,metodo_pago,numero_operacion,fecha_pago,estado,observacion) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=ConexionMySQL.conectar()){c.setAutoCommit(false);String cod=CodigoDAOUtil.siguiente(c,"pagos","codigo_pago","PAG");try(PreparedStatement p=c.prepareStatement(sql)){p.setString(1,cod);cargar(p,x,2);boolean ok=p.executeUpdate()>0;c.commit();return ok;}catch(Exception e){c.rollback();throw e;}}catch(Exception e){System.out.println("Error registrar pago: "+e.getMessage());return false;}}
 public List<Pago> listar(){List<Pago> l=new ArrayList<>();String sql="SELECT p.*,o.codigo_orden,CONCAT(o.codigo_orden,' - ',c.nombres,' ',c.apellidos) orden_descripcion FROM pagos p JOIN ordenes_servicio o ON o.id_orden=p.id_orden JOIN clientes c ON c.id_cliente=o.id_cliente ORDER BY p.id_pago DESC";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql);ResultSet r=p.executeQuery()){while(r.next())l.add(map(r));}catch(SQLException e){System.out.println("Error listar pagos: "+e.getMessage());}return l;}
 public boolean actualizar(Pago x){String sql="UPDATE pagos SET id_orden=?,monto=?,metodo_pago=?,numero_operacion=?,fecha_pago=?,estado=?,observacion=? WHERE id_pago=?";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){cargar(p,x,1);p.setInt(8,x.getIdPago());return p.executeUpdate()>0;}catch(SQLException e){System.out.println("Error actualizar pago: "+e.getMessage());return false;}}
 public boolean eliminar(int id){try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement("DELETE FROM pagos WHERE id_pago=?")){p.setInt(1,id);return p.executeUpdate()>0;}catch(SQLException e){System.out.println("Error eliminar pago: "+e.getMessage());return false;}}
 public Pago buscarPorId(int id){String sql="SELECT p.*,o.codigo_orden,CONCAT(o.codigo_orden,' - ',c.nombres,' ',c.apellidos) orden_descripcion FROM pagos p JOIN ordenes_servicio o ON o.id_orden=p.id_orden JOIN clientes c ON c.id_cliente=o.id_cliente WHERE p.id_pago=?";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}catch(SQLException e){return null;}}
 private void cargar(PreparedStatement p,Pago x,int i)throws SQLException{p.setInt(i++,x.getIdOrden());p.setDouble(i++,x.getMonto());p.setString(i++,x.getMetodoPago());if(x.getNumeroOperacion()==null||x.getNumeroOperacion().isBlank())p.setNull(i++,Types.VARCHAR);else p.setString(i++,x.getNumeroOperacion());p.setString(i++,x.getFechaPago());p.setString(i++,x.getEstado());if(x.getObservacion()==null||x.getObservacion().isBlank())p.setNull(i,Types.VARCHAR);else p.setString(i,x.getObservacion());}
 private Pago map(ResultSet r)throws SQLException{Pago x=new Pago();x.setIdPago(r.getInt("id_pago"));x.setCodigoPago(r.getString("codigo_pago"));x.setIdOrden(r.getInt("id_orden"));x.setCodigoOrden(r.getString("codigo_orden"));x.setOrdenDescripcion(r.getString("orden_descripcion"));x.setMonto(r.getDouble("monto"));x.setMetodoPago(r.getString("metodo_pago"));x.setNumeroOperacion(r.getString("numero_operacion"));x.setFechaPago(r.getString("fecha_pago"));x.setEstado(r.getString("estado"));x.setObservacion(r.getString("observacion"));return x;}
}
