package dao;
import conexion.ConexionMySQL; import modelo.Usuario; import java.sql.*; import java.util.*;
public class UsuarioDAO {
 public Usuario validarLogin(String usuario,String clave){String sql="SELECT * FROM usuarios WHERE (usuario=? OR dni=?) AND clave=? AND estado='Activo'";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,usuario);p.setString(2,usuario);p.setString(3,clave);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}catch(SQLException e){System.out.println("Error login: "+e.getMessage());return null;}}
 public boolean registrar(Usuario u){String sql="INSERT INTO usuarios(dni,nombre,usuario,clave,rol,correo,telefono,estado) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,u.getDni());p.setString(2,u.getNombre());p.setString(3,u.getUsuario());p.setString(4,u.getClave());p.setString(5,u.getRol());setNullable(p,6,u.getCorreo());setNullable(p,7,u.getTelefono());p.setString(8,u.getEstado());return p.executeUpdate()>0;}catch(SQLException e){System.out.println("Error registrar usuario: "+e.getMessage());return false;}}
 public List<Usuario> listar(){List<Usuario> l=new ArrayList<>();try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement("SELECT * FROM usuarios ORDER BY id_usuario DESC");ResultSet r=p.executeQuery()){while(r.next())l.add(map(r));}catch(SQLException e){System.out.println("Error listar usuarios: "+e.getMessage());}return l;}
 public boolean actualizar(Usuario u){boolean clave=u.getClave()!=null&&!u.getClave().isBlank();String sql=clave?"UPDATE usuarios SET dni=?,nombre=?,usuario=?,clave=?,rol=?,correo=?,telefono=?,estado=? WHERE id_usuario=?":"UPDATE usuarios SET dni=?,nombre=?,usuario=?,rol=?,correo=?,telefono=?,estado=? WHERE id_usuario=?";try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement(sql)){int i=1;p.setString(i++,u.getDni());p.setString(i++,u.getNombre());p.setString(i++,u.getUsuario());if(clave)p.setString(i++,u.getClave());p.setString(i++,u.getRol());setNullable(p,i++,u.getCorreo());setNullable(p,i++,u.getTelefono());p.setString(i++,u.getEstado());p.setInt(i,u.getIdUsuario());return p.executeUpdate()>0;}catch(SQLException e){System.out.println("Error actualizar usuario: "+e.getMessage());return false;}}
 public boolean eliminar(int id){try(Connection c=ConexionMySQL.conectar();PreparedStatement p=c.prepareStatement("DELETE FROM usuarios WHERE id_usuario=?")){p.setInt(1,id);return p.executeUpdate()>0;}catch(SQLException e){System.out.println("Error eliminar usuario: "+e.getMessage());return false;}}
 private Usuario map(ResultSet r)throws SQLException{Usuario u=new Usuario();u.setIdUsuario(r.getInt("id_usuario"));u.setDni(r.getString("dni"));u.setNombre(r.getString("nombre"));u.setUsuario(r.getString("usuario"));u.setClave(r.getString("clave"));u.setRol(r.getString("rol"));u.setCorreo(r.getString("correo"));u.setTelefono(r.getString("telefono"));u.setEstado(r.getString("estado"));return u;}
 private void setNullable(PreparedStatement p,int i,String v)throws SQLException{if(v==null||v.isBlank())p.setNull(i,Types.VARCHAR);else p.setString(i,v);}
}
