package vista;
import controlador.UsuarioController; import modelo.Usuario;
import javax.swing.*; import javax.swing.table.*; import java.awt.*; import java.util.List;
public class FormUsuarios extends JFrame {
 private JTextField txtId,txtDni,txtNombre,txtUsuario,txtCorreo,txtTelefono; private JPasswordField txtClave; private JComboBox<String> cboRol,cboEstado; private JTable tabla; private DefaultTableModel modelo; private final UsuarioController controller=new UsuarioController(); private final Usuario sesion;
 public FormUsuarios(Usuario u){sesion=u;setTitle("RV Solutions - Gestión de Usuarios");setSize(1240,740);setDefaultCloseOperation(DISPOSE_ON_CLOSE);setExtendedState(MAXIMIZED_BOTH);EstilosRV.aplicarIconoVentana(this);inicializar();listar();}
 private void inicializar(){BackgroundPanel fondo=new BackgroundPanel("assets/fondos/administrador.png");fondo.setLayout(new BorderLayout(16,16));fondo.setBorder(BorderFactory.createEmptyBorder(14,16,16,16));JPanel header=EstilosRV.crearPanelTarjeta(new BorderLayout());JLabel t=new JLabel("Gestión de Usuarios");EstilosRV.estilizarTitulo(t);header.add(t,BorderLayout.WEST);fondo.add(header,BorderLayout.NORTH);
 JPanel body=new JPanel(new BorderLayout(0,12));body.setOpaque(false);JButton n=new JButton("Nuevo"),e=new JButton("Editar"),d=new JButton("Eliminar"),x=new JButton("Descargar reporte");JPanel card=EstilosRV.crearPanelTarjeta(new BorderLayout(0,12));card.add(EstilosRV.crearCabeceraTablaModulo("Lista de Usuarios",n,e,d,x),BorderLayout.NORTH);modelo=new DefaultTableModel(new String[]{"DNI","Nombre","Usuario","Rol","Correo","Teléfono","Estado","ID interno"},0){public boolean isCellEditable(int r,int c){return false;}};tabla=new JTable(modelo);EstilosRV.estilizarTabla(tabla);tabla.setRowHeight(42);tabla.getColumnModel().getColumn(6).setCellRenderer(new EstadoRenderer());tabla.removeColumn(tabla.getColumnModel().getColumn(7));JScrollPane sp=new JScrollPane(tabla);EstilosRV.estilizarScroll(sp);card.add(sp,BorderLayout.CENTER);body.add(card,BorderLayout.CENTER);fondo.add(body,BorderLayout.CENTER);n.addActionListener(q->{limpiar();form(false);});e.addActionListener(q->form(true));d.addActionListener(q->eliminar());x.addActionListener(q->ReporteUtil.exportarTablaCSV(this,tabla,"reporte_usuarios"));tabla.getSelectionModel().addListSelectionListener(q->seleccionar());setContentPane(fondo);}
 private JPanel formulario(){JPanel p=new JPanel(new GridBagLayout());p.setOpaque(false);GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(7,7,7,7);g.fill=GridBagConstraints.HORIZONTAL;g.weightx=1;txtId=new JTextField();txtId.setVisible(false);txtDni=new JTextField();txtNombre=new JTextField();txtUsuario=new JTextField();txtClave=new JPasswordField();txtCorreo=new JTextField();txtTelefono=new JTextField();cboRol=new JComboBox<>(new String[]{"Administrador","Tecnico"});cboEstado=new JComboBox<>(new String[]{"Activo","Inactivo"});for(JTextField f:new JTextField[]{txtDni,txtNombre,txtUsuario,txtClave,txtCorreo,txtTelefono})EstilosRV.estilizarCampo(f);EstilosRV.estilizarCombo(cboRol);EstilosRV.estilizarCombo(cboEstado);String[] l={"DNI (8 dígitos):","Nombre:","Usuario:","Clave:","Correo:","Teléfono:","Rol:","Estado:"};JComponent[] c={txtDni,txtNombre,txtUsuario,txtClave,txtCorreo,txtTelefono,cboRol,cboEstado};for(int i=0;i<l.length;i++){g.gridx=(i%2)*2;g.gridy=i/2;JLabel z=new JLabel(l[i]);EstilosRV.estilizarEtiqueta(z);p.add(z,g);g.gridx++;p.add(c[i],g);}return p;}
 private void form(boolean editar){int row=tabla.getSelectedRow();if(editar&&row<0){JOptionPane.showMessageDialog(this,"Seleccione un usuario.");return;}String[] vals=null;if(editar){int m=tabla.convertRowIndexToModel(row);vals=new String[8];for(int i=0;i<8;i++)vals[i]=String.valueOf(modelo.getValueAt(m,i));}JPanel fp=formulario();if(editar){txtDni.setText(vals[0]);txtNombre.setText(vals[1]);txtUsuario.setText(vals[2]);cboRol.setSelectedItem(vals[3]);txtCorreo.setText("null".equals(vals[4])?"":vals[4]);txtTelefono.setText("null".equals(vals[5])?"":vals[5]);cboEstado.setSelectedItem(vals[6]);txtId.setText(vals[7]);}JDialog dlg=new JDialog(this,editar?"Actualizar usuario":"Nuevo usuario",true);JPanel cont=new EstilosRV.RoundedPanel(new BorderLayout(0,16),Color.WHITE,28);cont.setBorder(BorderFactory.createEmptyBorder(24,26,22,26));JLabel title=new JLabel(editar?"Actualizar Usuario":"Nuevo Usuario");title.setFont(new Font("Segoe UI",Font.BOLD,24));cont.add(title,BorderLayout.NORTH);cont.add(fp,BorderLayout.CENTER);JPanel acc=new JPanel(new FlowLayout(FlowLayout.RIGHT));acc.setOpaque(false);JButton can=EstilosRV.crearBotonRedondeado("Cancelar",false),sav=EstilosRV.crearBotonRedondeado(editar?"Actualizar":"Guardar",true);can.addActionListener(q->dlg.dispose());sav.addActionListener(q->{boolean ok=editar?actualizar():guardar();if(ok)dlg.dispose();});acc.add(can);acc.add(sav);cont.add(acc,BorderLayout.SOUTH);dlg.setContentPane(cont);dlg.setSize(820,520);dlg.setLocationRelativeTo(this);dlg.setVisible(true);}
 private boolean guardar(){String dni=txtDni.getText().trim();boolean ok=controller.registrarUsuario(dni,txtNombre.getText(),txtUsuario.getText(),new String(txtClave.getPassword()),String.valueOf(cboRol.getSelectedItem()),txtCorreo.getText(),txtTelefono.getText(),String.valueOf(cboEstado.getSelectedItem()));JOptionPane.showMessageDialog(this,ok?"Usuario registrado correctamente.":"No se pudo registrar. Verifique DNI de 8 dígitos y datos únicos.");if(ok)listar();return ok;}
 private boolean actualizar(){boolean ok=controller.actualizarUsuario(Integer.parseInt(txtId.getText()),txtDni.getText(),txtNombre.getText(),txtUsuario.getText(),new String(txtClave.getPassword()),String.valueOf(cboRol.getSelectedItem()),txtCorreo.getText(),txtTelefono.getText(),String.valueOf(cboEstado.getSelectedItem()));JOptionPane.showMessageDialog(this,ok?"Usuario actualizado correctamente.":"No se pudo actualizar.");if(ok)listar();return ok;}
 private void eliminar(){int r=tabla.getSelectedRow();if(r<0){JOptionPane.showMessageDialog(this,"Seleccione un usuario.");return;}int id=Integer.parseInt(String.valueOf(modelo.getValueAt(tabla.convertRowIndexToModel(r),7)));if(sesion!=null&&id==sesion.getIdUsuario()){JOptionPane.showMessageDialog(this,"No puede eliminar la sesión activa.");return;}if(JOptionPane.showConfirmDialog(this,"¿Eliminar usuario?","Confirmar",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){boolean ok=controller.eliminarUsuario(id,sesion==null?0:sesion.getIdUsuario());JOptionPane.showMessageDialog(this,ok?"Usuario eliminado.":"No se pudo eliminar.");if(ok)listar();}}
 private void listar(){modelo.setRowCount(0);for(Usuario u:controller.listarUsuarios())modelo.addRow(new Object[]{u.getDni(),u.getNombre(),u.getUsuario(),u.getRol(),u.getCorreo(),u.getTelefono(),u.getEstado(),u.getIdUsuario()});}
 private void seleccionar(){} private void limpiar(){if(tabla!=null)tabla.clearSelection();}
 private static class EstadoRenderer extends DefaultTableCellRenderer{public Component getTableCellRendererComponent(JTable t,Object v,boolean s,boolean f,int r,int c){Color[] cs=EstilosRV.coloresEstado(String.valueOf(v));return EstilosRV.crearBadgeEstado(String.valueOf(v),cs[0],cs[1],s?t.getSelectionBackground():Color.WHITE);}}
}
